// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.CommandLine")>]
[<assembly: AssemblyProductAttribute("FSharp.CommandLine")>]
[<assembly: AssemblyDescriptionAttribute("A framework for building command line application in F#")>]
[<assembly: AssemblyVersionAttribute("1.1.3059.9094")>]
[<assembly: AssemblyFileVersionAttribute("1.1.3059.9094")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.CommandLine"
    let [<Literal>] AssemblyProduct = "FSharp.CommandLine"
    let [<Literal>] AssemblyDescription = "A framework for building command line application in F#"
    let [<Literal>] AssemblyVersion = "1.1.3059.9094"
    let [<Literal>] AssemblyFileVersion = "1.1.3059.9094"
    let [<Literal>] AssemblyConfiguration = "Release"
