// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("3.3.3805.29570")>]
[<assembly: AssemblyFileVersionAttribute("3.3.3805.29570")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "3.3.3805.29570"
    let [<Literal>] AssemblyFileVersion = "3.3.3805.29570"
