// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("3.1.3294.2201")>]
[<assembly: AssemblyFileVersionAttribute("3.1.3294.2201")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "3.1.3294.2201"
    let [<Literal>] AssemblyFileVersion = "3.1.3294.2201"
