// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("3.0.3292.28805")>]
[<assembly: AssemblyFileVersionAttribute("3.0.3292.28805")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "3.0.3292.28805"
    let [<Literal>] AssemblyFileVersion = "3.0.3292.28805"
